version: '3'

services:
  db:
    image: 'postgres'
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=notification
  cache:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_db_data:/data
volumes:
  redis_db_data:
    external: false